name: AgOpenGps.Legacy.CI

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild AgOpenGPS -p:Configuration=Release
